name: build-and-push-docker

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    name: Build arm64 image and push
    runs-on: ubuntu-24.04-arm64
    timeout-minutes: 90
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # QEMU not required on native arm64 runner

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: vars
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Compute image name (lowercase)
        id: img
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY}"
          echo "image=${IMAGE,,}" >> $GITHUB_OUTPUT

      - name: Build and push (arm64 only)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.img.outputs.image }}:${{ steps.vars.outputs.tag }}
            ${{ steps.img.outputs.image }}:latest
          build-args: |
            TARGETPLATFORM=linux/arm64
