name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build Web
        run: |
          cd frontend/jellybelly-web
          npm ci
          npm run build
          mkdir -p ../../public
          cp -R dist/* ../../public
      - name: Install Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.10'
      - name: Build Server
        run: swift build -c release
      - name: Package
        run: |
          mkdir -p artifact
          cp .build/release/JellybellyServer artifact/
          cp -R public artifact/public
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jellybelly-linux-amd64
          path: artifact

  docker:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.ref_name }}


